name: Install Dependencies
description: Install Node Dependencies


runs:
  using: composite
  steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        node-version: '14.x'

    - name: Install Dependencies
      run: npm install
      shell: bash