name: Provide Infrastructure
description: Provide a given environment (e.g., prod, staging)

inputs:
  environment:
    required: true

runs:
  using: composite
  steps:

    - name: Apply terraform
      run: |
        cd terraform/${{inputs.environment}}
        terraform init
        terraform apply -auto-approve
      shell: bash

    - name: Notify
      uses: ./.github/actions/notify
      with:
        email: team@acme.com
        message: "Deploy of ${{github.repository}} on ${{ inputs.environment }} done. You can verify logs here: https://${{ github.repository }}/actions/runs/${{ github.run_id }}"
        title: "Deploy of ${{github.repository}} on ${{ inputs.environment }} done"