name: Build Microservice Images

on: 
  workflow_call:
    inputs:
      services:
        description: 'List of microservices to be build. Must be in JSON format, e.g., ["ms1","ms2"]'
        type: string
        required: true
      region:
        description: 'Region to publish the artifacts'
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(inputs.services) }}
    steps:
      
      - uses: ./.github/actions/build-image
        with:
          image: ${{ matrix.service }}

  test-images:
    runs-on: ubuntu-latest 
    needs: [build-images]
    strategy:
      matrix:
        service: ${{ fromJson(inputs.services )}}
    steps:

      - uses: ./.github/actions/test-image
        with:
          image: ${{ matrix.service }}

  upload-images:
    runs-on: ubuntu-latest
    needs: [test-images]
    strategy: 
      matrix:
        service: ${{ fromJson(inputs.services)}}
    steps:

      - uses: ./.github/actions/upload-to-registry
        with:
          image: ${{ matrix.service }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: ${{ inputs.region }}
        
  notify-errors:
    if: failure()
    needs: [build-images, test-images, upload-images]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/notify
        with:
          email: team@acme.com
          message: "Build Failed. Please verify here: https://${{ github.repository }}/actions/runs/${{ github.run_id }}"
          title: 'Build on ${{github.repository}} Failed'