name: Pipeline CI/CD ACME

on:
  push:
    branches:
      - develop
      - release
      - main

jobs:

  tests:
    uses: ./.github/workflows/test.yml
    secrets:  
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

  build:
    if: github.ref != 'refs/heads/develop'
    uses: ./.github/workflows/build-microservices-images.yml
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs: [tests]
    with:
      services: '["microservice1", "microservice2"]'
      region: ${{ vars.AWS_REGION }}