name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          #tries to use node version from .nvmrc or .node-version file from root. use 14.x if neither exists.
          node-version-file: '.nvmrc'
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Unity Tests
        run: npm run test:unit

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Run Performance Tests
        run: ab -n 1000 -c 10 http://localhost:3000/

  build-microservices-images:
    if: github.ref == 'refs/heads/develop'
    needs: test
    uses: ./.github/workflows/build-microservices-images.yml