name: Test

on:
  workflow_call:

jobs:
  run-primary-tests:
    runs-on: ubuntu-latest
    steps:

      - uses: ./.github/actions/run-primary-tests

  run-sonar-scan:
    if: github.ref != 'refs/heads/develop'
    needs: [run-primary-tests]
    uses: ./.github/workflows/run-sonar.yml
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}